### ISSUE TITLE
SimpleExample fails with errors

### ISSUE THREAD

**Issue by rhys-vdw** [ExpressoBits/EBConsole#21]
When I import the simple example sample I get the following errors:

![image](https://user-images.githubusercontent.com/822105/171600898-4834fb82-881e-4174-b096-39aaa7b08f62.png)

e.g.

> Assets\Samples\EB Console\1.3.2\Simple example\Scripts\TestPrintLog.cs(13,16): error CS0176: Member 'Consoler.Logs' cannot be accessed with an instance reference; qualify it with a type name instead

I suspect this is because the sample has no asmdef? But when I add one that references your package the errors remain.

**Comment by rhys-vdw** [comment]
Oh, actually it simply contains errors! I think this may have happened because you've suffixed the folder with `~` in your project, so when you changed the API you got no compile errors from the sample code. Usually you would handle this by renaming the Sample folder only on release.

**Comment by scriptsengineer** [comment]
Fixed on 1.3.3, problem for missing asdmef as you mentioned , thanks @rhys-vdw for reporting
